os: linux
dist: xenial
language: cpp
compiler:
  - gcc

addons:
  sonarcloud:
    organization: "shyam-lab"
    token: ${SONAR_TOKEN}

script:
  - wget http://www.fftw.org/fftw-3.3.8.tar.gz
  - tar -xzvf fftw-3.3.8.tar.gz
  - cd fftw-3.3.8
  - ./configure --prefix=/home/travis/build/shyam-lab/lb-unofficial/fftw-3.3.8/
  - make
  - make install
  - build-wrapper-linux-x86-64 --out-dir bw-output make FFTW=/home/travis/build/shyam-lab/lb-unofficial/fftw-3.3.8/
  - sonar-scanner -X

cache:
  directories:
   - "$HOME/.sonar/cache"
