addons:
  sonarcloud:
    organization: shyam-lab
    token:
      secure: "o+02mGeOzUwAF1BN/pZm1wyU1kSjkVrttcpTcytKtIqk7cb8d/XIm9XFxSOaURf3d6D/+CUKYFND3TP44NgolBKL+F7ZIeCwyhpq1h3vikNP/fZ6j6qsA5xUByrujQh6GDLeAGr3smSIh8AWb5sC96F8eDc+rXpYBeGWatSj6X1eZxU5xcRzJIAYDdw8cxXn8C1n97AK6QdLhGp/8gciNuDLc7VOV6mEJuW/oqcEdevppe6X5hNQeoffMuvT+X7Pbd/xelBKzxyMaDBh1Ffd8zCiuuVa2YmEOHR6FhdqkiRgLjdw8ersXXmpDa4jMNEF1+m+MBZ4Jw3igJPOnXhXFDsNYtx25ViBEIdJYAQrHwAbPrC9ytJYKlElhELHT2IKFgU+3VuSY44RWDaG6Uy9KN/3UGBWQtki2iC3DOHOssG5e6cr/8LI3NC3W1ZNJoBQ/i6pFArsXL/7ZCVzX+st0ryyEiLnuGWTwuKqTWZUa4YW0SUtkX230fFzAVLTgU7fsSamrcSX2fPfuKqxBplwCi1yyUJlQVWiIcJyweOCnPKEX+vVVSYRd4b6YN3sW8P9NCpXfS8XGNFl7LScQ5wCAaxVBy8pBXvZjcED6AZHWL91gKodZe2O+uWbDagfdFjMsxsqnmvImCBdzmPiUpzVwuFXKSD1ymNoOLSGQiR4Kfk="
script:
- wget http://www.fftw.org/fftw-3.3.8.tar.gz
- tar -xzvf fftw-3.3.8.tar.gz
- cd fftw-3.3.8
- ./configure --prefix=/home/travis/build/shyam-lab/lb-unofficial/fftw-3.3.8/
- make
- make install
- build-wrapper-linux-x86-64 --out-dir bw-output make FFTW=/home/travis/build/shyam-lab/lb-unofficial/fftw-3.3.8/
- sonar-scanner -X -Dsonar.cfamily.build-wrapper-output=bw-output
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  global:
    secure: "jLq9SqlT3XMt/eivgcLZI8CU7LIPWFYaOmRNdNWvdaeMI2waMUQmAum8AQ+Y3f8R00YCCB1zmKQtaJ/XFZakKY5+cre5luRWH/Wj2mci53l992CCpRS210Q8MHWdJ1qz7+AhtYfN7N0j21/LGOfmjivCLPD7lS20wWKGS0p4LnKPVjcsNv1KzOGEMCJ6JZzM/Q23bMa9f8HxpJK2Nzmcbs60LqOzZld2DvvHwo0xd2olTbygFz08EZjx9DfpUpVL6SsseRkO2STgm3d/pZhGhNTnkUjmYrnQmdH11srjecMOiGTmw1JBkvAhxCA5dW6kgb6p5QxcjYtA/kmkyFc2hJlx/o88NbIFVjvs1sAjKvnnWrWzby9Y0AX8czSfKKFLZbo7eqapKk+DAASpOBKObvr8oewzKmPnD2k3XqxDr1BznCLaZW3F9nWsRWwEckxFzwIOeEAkpKCHNpmzDRrJQ8JN7S7XRpiKr4KIZuG59ecHTAgcchleYPMn8E+jNamRx+DiNwtemC6B8gY401Gt+RVbZ7LGjlYy7wgTv/rnuWzdH8jExMc8SONm/KnyzhmUeAufMnC7xRCfWLDO5+4YF+yNC6lb5WTZV0z+LguGg5cWcYALeTGYE8G94phaL/WV6t7m3n2m9xTGwXcBLwYE/mdiOuf0vCgNa5DM1cmRH28="
